### ISSUE TITLE
Fail to import WSR Puppeteer testkits since Yoshi 4.6.2

### ISSUE THREAD

**Issue by mosheKerbel** [wix/yoshi#1386] opened 2019-06-17 12:57 UTC
# 🐛 Bug Report

create-yoshi-app since version 4.6.2 introduces an issue with Puppeteer.

Try to import any kind of puppeteer testkit from WSR and you will get
```
 ReferenceError: document is not defined

      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:944:27
      at Object.<anonymous> (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1283:5)
      at Object.<anonymous> (node_modules/react-dom/test-utils.js:6:20)
```

You don't need to actually use the teskit for the error to be thrown
Just import this testkit for example:
```import { headingTestkitFactory } from 'wix-style-react/dist/testkit/puppeteer';```

You can do it on an empty yoshi project inside the ```simple.e2e.js```

### 🤔 Expected Behavior

Error should not be thrown after import, as it works fine in projects created with create-yoshi-app@4.6.0 

* Notice that some Puppeteer change was intorudced in [4.6.2 release](https://github.com/wix/yoshi/blob/master/CHANGELOG.md#462-2019-05-21), i don't know if it's related.

**Comment by shlomitc** [comment] 2019-07-07 18:10
I think I got the cause for the issue - it's `react-dom` version.

1. `create-yoshi-app`, brings `react-dom@16.8.0`.
2. In the WSR testkits/drivers, we use `react-dom/test-utils` (will explain later why)
3. In this specific version, `document.createElement('div')` is called right importing the module (at `node_modules/react-dom/cjs/react-dom-test-utils.development.js:944:27`).
4. in previous versions (like 16.4.0) this happens only when invoking some function and not immediately.
5. when downgrading to previous 16.4.0 or in the latest 16.8.6, everything works well.


here's a simple reproducible code
```jsx
// src/components/App.js
import React from 'react';
import s from './App.scss';
import Button from 'wix-style-react/Button';
import Text from 'wix-style-react/Text';

class App extends React.Component {
  state = {
    wasClicked: false,
  };

  render() {
    return (
      <div className={s.root}>
        <Button
          dataHook="wsr-button"
          onClick={() => this.setState({ wasClicked: true })}
        >
          hello
        </Button>
        {this.state.wasClicked && <Text dataHook="wsr-text">clicked</Text>}
      </div>
    );
  }
}

export default App;
```

```js
//__tests__/browser.e2e.js
import {
  buttonTestkitFactory,
  textTestkitFactory,
} from 'wix-style-react/dist/testkit/puppeteer';

describe('React application', () => {
  it('should display title', async () => {
    await page.goto(app.getUrl('/'));
    await page.waitForSelector('[data-hook="wsr-button"]');
    const buttonDriver = await buttonTestkitFactory({
      page,
      dataHook: 'wsr-button',
    });
    await buttonDriver.click();
    const textDriver = await textTestkitFactory({ page, dataHook: 'wsr-text' });

    expect(await textDriver.getValue()).toEqual('clicked');
  });
});
```

@ranyitz - let's update our generators and it should solve the issue

**Comment by ranyitz** [comment] 2019-07-09 13:42
@shlomitc First, if you think that upgrading the version of react-dom in the generator will solve the problem then let's upgrade it, upgrading this version is a good thing in general and we are always open for PRs.

Here is a PR https://github.com/wix/yoshi/pull/1452
_________________

Regarding the issue itself, I'll share my thoughts:

**The environment:** When we talk about `e2e` tests we talk about `node` environment, we bootstrap a browser via puppeteer and control the browser to perform operations. The assertions themselves run in **node**.

`react-dom` is used to render the components to the dom, in `e2e` context it will run in the browser.

The error comes from `node`, and not from the `browser`:

![image](https://user-images.githubusercontent.com/11733036/60890586-3cae5c80-a264-11e9-9854-9ae4fea49bbc.png)

The fact that `react-dom` version caused a problem in `node` is legitimate when talking about component tests. In component tests we imitate the dom using `jsdom` but actually running in a `node` process. **This is not the case**.

We should not see `react-dom` in `node` context when talking about `e2e` tests and puppeteer.

But still, I wanted to know why this `react-dom` is there in the first place.

The answer is `uni-driver`, you can see in this example:

https://github.com/wix/wix-ui/blob/7ba7cb7af5a9e83cf774a08a50070b1e403e660d/packages/wix-ui-core/src/components/file-picker-button/test/FilePickerButton.uni.driver.ts#L7

When using `uni-driver` we first import `react-dom`, `protractor` and more ... Even if this is not relevant to us at all.

I have to say that this is a bad pattern in general because it makes you import many things to a test, even if you don't need them, and raise problems like the one above.
_____________________________________

`react-dom/test-utils` though, is being used in both `node` and the `browser`, probably because of https://reactjs.org/docs/react-dom-server.html.

And therefore this issue was [fixed](https://github.com/facebook/react/pull/14768) in version `16.8.1`.

This is **not the case** in `WSR` testkits.
____________________________________

I'm closing this issue because it is not a Yoshi issue. If you need any help at fixing those problems at `WSR`/`wix-ui-core` codebase let me know.

**Closed by ranyitz** 2019-07-09 13:42 UTC

**Comment by shlomitc** [comment] 2019-07-09 14:33
@ranyitz thanks for the well-explained comment.

Regarding the WSR drivers issue where both `react-dom` and `puppeteer` are used in `unidriver` drivers, this is due to a gradual migration strategy we're doing to our drivers and the consumers' migration. eventually, the puppeteer uni-drivers will not contain `react-dom` at all, but this will take time.

@mosheKerbel - please keep this in mind and add this to the drivers roadmap, when we finish the first phase of drivers migration, we want to be sure we don't have this mixture.

Thanks
