### ISSUE TITLE
create-yoshi-app react dependency too old

### ISSUE THREAD

**Issue by amitdahan** [wix/yoshi#892] opened 2018-12-24 10:55 UTC
# 🐛 Bug Report

### 😯 Current Behavior
Generators for client projects start with react 15.X

### 🤔 Expected Behavior
Current viewer uses react 16.6.X and business manager is about to merge usage of react 16.4.X.
For better cache management and version alignment - this should be properly aligned with the rest of Wix.

### 💁 Possible Solution
Update generators to use enzyme 3 + react 16.

**Comment by ronami** [comment] 2019-01-15 12:58
Duplicate of #651. We'll be happy to get PR and merge it as soon as Business Manager is using React 16. cc @shlomitc.

**Closed by ronami** 2019-01-15 12:58 UTC
