### ISSUE TITLE
Yoshi is consuming 50% CPU when no files are edited

### ISSUE THREAD

**Issue by astrauka** [wix/yoshi#139] opened 2017-06-29 14:24 UTC
Not sure if that's even an issue, it only matters when working on battery.

<img width="1360" alt="screen shot 2017-06-29 at 17 22 05" src="https://user-images.githubusercontent.com/1308928/27692582-be61e470-5cef-11e7-99c2-b460309c8df9.png">

How to reproduce:
* start development server
* watch top (screenshot is made with `htop`)

**Comment by tqmukas** [comment] 2017-06-30 07:37
Duplicate of issue #39

**Closed by tqmukas** 2017-06-30 07:37 UTC
