### ISSUE TITLE
Provide a standard way to consume Stylable's output

### ISSUE THREAD

**Issue by nitayneeman** [wix/yoshi#1902] opened 2020-01-28 15:02 UTC
# 🙋 Feature Request

Hey,

I've already posted in your Slack channel, but I always prefer GitHub for making discussions :)

## Context
I’m working right now on guidelines for making mobile-friendly web applications using wix-style-react, when one of the aspects is SSR.

I know that you don’t support SSR at this point, but we’d love to hear your opinion anyway.

In wix-style-react, we use both CSS Modules and Stylable to style our components. This means that when an application is rendered using SSR, it makes sense to separate the CSS outputs out of the bundle (and that actually happens defaultly because of `separateCss`, which is great).

## Problem

The thing is, that the separated `app.css` doesn’t include the output of Stylable, whereas it arrives with the JS bundle itself (https://github.com/wix/yoshi/pull/329) and rendered at runtime.

We're looking for a standard way to consume Styleable's output specifically (mainly for SSR) - such we could suggest whole-heartedly. 😉

## Possible Solution 1

Exporting Stylable’s output into a separate file using `enhancedTpaStyle`.

That's what we currently instruct our consumers to do:
https://github.com/wix/wix-style-react/blob/master/docs/FAQ/README.md#components-do-not-have-styling-in-the-first-render-of-server-side-rendering-ssr

### Pros 
- Stylable output doesn't arrive with the JS bundle but in a separate file, beside `app.css`, so that both could be loaded explicitly when rendering with SSR

### Cons
- This isn't the main purpose of `enhancedTpaStyle` but just a side-effect
- Could be more side-effects that we don't actually want

## Possible Solution 2

Exporting Stylable’s output into a separate file using a dedicated configuration such as `stylableSeparateCss`.

Basically it means to expose the following configuration:
https://github.com/wix/yoshi/blob/9b437130ed28b3b26def37922eefec811b54fde2/packages/yoshi-common/src/webpack.config.ts#L229

### Pros 
- Same of the first solution (a separate file)
- We don't have the side-effects of `enhancedTpaStyle`

### Cons
-  Another configuration to maintain and document

## Possible Solution 3

Theoretically, Stylable’s output could be concatenated to `app.css` ahead of time, pretty much like happens for other CSS preprocessors - which means that would happen defaultly when using `separateCss`, instead of ignoring in case of Stylable (https://github.com/wix/yoshi/issues/309).

### Pros 
- All styles are placed in a single stylesheet per entry, that's easily consumable
- Would be treated conventionally like any other CSS preprocessor

### Cons
- Demands assistance of the Stylable team (https://github.com/wix/stylable/issues/442 seems to be still open)?
- Inconsistent behavior compared to `enhancedTpaStyle`

## Suggestion

Personally I would go with the second possible solution because that's a quick-win. But, in the long term, I would definitely consider thinking about the third. Either way, I'd love to help you with the effort if needed (and accepted by you).

Let me know what you think 🙂

CC: @shlomitc

**Comment by shlomitc** [comment] 2020-01-29 14:19
Option 2 sounds like a quick win for the short term and one that we can suggest to our users who want to improve their JS bundle size

Option 3 sounds amazing but will require more work of course. I do want to mention that there was an attempt to create a `standalone` version of our component libraries (based on [this](https://github.com/wix-a/wsr-output-standalone) RFC.
The output of the standalone version would provide a valid `.css` file instead of the `.st.css`. This would make bundling of the styles to `app.css` file.
See also this PR which was the beginning of the effort (https://github.com/wix/wix-ui/pull/1348)

**Comment by ranyitz** [comment] 2020-02-12 14:51
Hey @shlomitc @nitayneeman I'm truly sorry that the response on this issue was delayed in 2 weeks. I wanted to give it more thought and couldn't find the time.

I'm ok with going on **option 2**. It will let you continue and we'll be able to think about this problem deeper in the future.

@nitayneeman feel free to add a PR, if you need any help with creating the PR feel free to contact me.

**Comment by mykas** [comment] 2020-02-13 08:48
I just want to add something here that I've encountered while using `enhancedTpaStyle`.

When we migrated some wix-style-react projects to named-imports and yoshi config had `enhancedTpaStyle:true` the dev server just hangs indefinitely. Added some console.logs in yoshi start scripts and it seems the hanging stuff comes from webpack-dev-server. 

No idea why though 🤷‍♂

**Comment by shlomitc** [comment] 2020-02-13 12:00
@mykas - can you create a reproducible example or share the failing project? If that's the case, we should fix it

**Comment by mykas** [comment] 2020-02-13 12:31
I am not able provide an open source based yoshi project, so I will just tell you where to get it. Find wix-style-react-mobile under our private org. 

1. Clone the repo
2. Checkout to `named-imports`
3. Install node modules
4. npm start

The yoshi start command will hang forever.

**Comment by shlomitc** [comment] 2020-02-13 14:37
We can share the link, no problem: https://github.com/wix-private/wix-style-react-mobile/tree/named-imports

**Comment by shlomitc** [comment] 2020-02-14 07:50
@ranyitz - do you want us to create a separate issue to tackle the hanging server issue?

**Comment by mykas** [comment] 2020-02-19 08:59
@ranyitz @shlomitc the issue with `enhancedTpaStyle:true` hanging on named-imports is solved. The cause: one of our stylable files in dist had syntax issue which made the enhancedTpaStyle plugin to hang.

**Comment by ranyitz** [comment] 2020-02-19 16:11
@shlomitc @mykas I think that if we want to talk about the "hanging server" issue, let's do it in a different issue. (If it's already solved, then awesome.)

**Comment by ranyitz** [comment] 2020-03-09 13:50
Fixed on #2010

**Closed by ranyitz** 2020-03-09 13:50 UTC
Labels: :wave: Help wanted, 👶 Good first issue, 🙋 Feature Request
