### ISSUE TITLE
Allow different `--server` entry points

### ISSUE THREAD

**Issue by carl-e** [wix/yoshi#1491] opened 2019-08-08 19:06 UTC
# 🐛 Bug Report

Heya, we over at DeviantArt have been using yoshi quite a awhile now and we're attempting to update to the app-flow setup.

We've hit some trouble tho in that we've got two different server entry points:
- One that is our standard server/SSR configuration (now called `server.js`)
- And a second that is similar but uses a mocked, testkit-based api so we don't need our VM-based api server running with it (called `server-dev.js`)

I've gotten the first flow working well enough with only some changes to our startup files. The second flow that uses `server-dev.js` has been more difficult.

### 😯 Current Behavior

If I'm attempting to start yoshi and the app with `server-dev.js`, I'm using an npm script like this:
```
  "scripts": {
    "start:novm": "yoshi start --server=server-dev.js",
    ...
  },
```
This will transpile and rebundle the app but use `src/server.js` as the bundle entry point instead of `src/server-dev.js` with the final bundle ending up at `dist/server.js`.

I think this is being caused by the `server` (or the alias `entry-point`) not being used in the webpack server bundle build and `server` or `dev/server` being the only actual options.

### 🤔 Expected Behavior

That `src/server-dev.js` would be used as the entry point for the bundle and (optionally but not a must-have) `dist/server-dev.js` would be the name of the final bundle.

### 🔦 Context 

There's really no way for us to support these two configurations under appFlow the way we have before. Without a fix for this I'm not sure how we'd be able to use the testkit-based development server.

### 💁 Possible Solution 

I've gotten yoshi working as expected by using the changes here:
https://gist.github.com/carl-e/e85e8581869c6520e1e92de56bc4c2a1

### 👣 Steps to Reproduce 

- In a working yoshi appFlow app, 
- copy you're entry point file (e.g. `src/server.js` to `src/server-copy.js`) 
- and add a `console.log` statement somewhere inside it (e.g. `console.log("hello")`). 
- If you then `yoshi start --server server-copy.js`, you'll see no log output. 
- (You could also look at `dist/server.js` and note there's no log statement in the bundled entry point.)

### 🌍 Your Environment

```
$ ./node_modules/.bin/yoshi info

  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: Not Found
  Browsers:
    Chrome: Not Found
    Firefox: 68.0.1
    Safari: 12.1.2
  npmPackages:
    @storybook/core:  5.0.11
    @storybook/react: 5.0.11 => 5.0.11
    babel-preset-yoshi:  4.10.2
    eslint-config-yoshi:  4.9.5
    eslint-config-yoshi-base:  4.4.2
    jest-yoshi-preset: Not Found
    react-scripts:  2.1.0
    storybook: Not Found
    tslint-config-yoshi:  4.4.3
    tslint-config-yoshi-base:  4.4.3
    typescript: ~3.5.0 => 3.5.3
    webpack:  4.38.0
    yoshi-config:  4.10.5
    yoshi-helpers:  4.10.5
    yoshi-runtime: ^1.0.217 => 1.0.217

 Zero config 🛴
```

**Comment by carl-e** [comment] 2019-08-09 18:05
By the way, I've got a commit ready to make a PR if you folks think it'd help. Happy to do it and let me know! Thanks

**Comment by ranyitz** [comment] 2019-08-11 09:14
Hey @carl-e, Thanks for opening an issue! It's great that you're attempting to move to the app-flow! We're very excited about it and we believe it will help you to move much faster as you work on your app!
___________________

I'll try to explain what Yoshi does today by looking at the [fullstack template](https://github.com/wix/yoshi/tree/master/packages/create-yoshi-app/templates/fullstack/javascript) (which seems to be the most similar to your use-case)

#### Production
* There is an `index.js` file which is the file that runs in production (e.g. `node index.js`)

* This `index.js` file [loads an express](https://github.com/wix/yoshi/blob/master/packages/create-yoshi-app/templates/fullstack/javascript/index.js#L10) app (which is bundled to `dist/server`)

#### Development
* There is an `index-dev.js` file which runs the `bootstrapServer` function which [runs a testkit](https://github.com/wix/yoshi/blob/master/packages/create-yoshi-app/templates/fullstack/javascript/environment.js#L16) that accepts the `index.js` file. So it is actually a wrapper above the same code that runs in production. (The bundled express app - `server.js` and the production entry point - `index.js` )

____________________________________

**So what Yoshi does?**

1. Bundles whatever is in `src/server.js`/`dev/server.js` into `dist/server` bundle.
2. During `yoshi start`, you can choose a `server/entry-point` for Yoshi to run. It assumes that the code there should bootstrap a server and waits for a port (`process.env.PORT`) to be captured before running anything else.

_________________________

I know that the current Yoshi configuration is weird. This is mostly due to legacy and some coupling to the `node_platform` APIs. @ronami & @netanelgilad have some great ideas to how we can solve it, and I'm sure that in the future we'll figure out a better and simpler way to work with this setup.

__________________________

While enabling multiple `--server` points or creating another bundle for development may be a good solution I prefer that you'll try to use the method above as a first step. If this is impossible to do, please write here and we'll discuss it. The next step would be to discuss how we can simplify the API and possible give more features for development mode.

Let me know what you think.

**Comment by carl-e** [comment] 2019-08-12 21:53
Hi, Ran and thanks for responding.  I like yoshi and it has handled our builds well.

The short form is that, (1) even in the best case, `server` will always be used as the entry point so there's no way to have any other entry points.

That's because there are only two possible, hard-coded base filenames that yoshi will use as a bundle entry point: `server.{js,ts}` or `dev/server.{js,ts}`. And, _even if you use those hard-coded names_, when you have both files the lookup will use `.find(exists)` and `server.js` is found first.

Also, (2) I'd consider the `server`/`entry-point` cli argument to be broken/bugged because it's not actually being used for what it says it's for.

It's possible I missed a step or setting and, if so, I'd love to hear it - but please read on and follow the links to see if my understanding is correct and there might be an issue.


### How it works for the default entry point as I understand it
Let me back up. Let's say I have a setup that's a) as close as possible to the ideal situation for yoshi but b) has two different servers that a dev should be able to launch from our apps: server.js and dev/server.js

#### Configuring webpack to build the server bundle
Here's the flow of these scripts as I've been seeing them happen starting with **first entry point**, `server.js`. First, the server bundle is built from a configuration assembled when the dev calls `yoshi start`:
- `yoshi start` calls command/start-app because our `projectType` is now `app`
- a webpack config object is built to create a server bundle by calling `webpack.config` here: https://github.com/wix/yoshi/blob/master/packages/yoshi/config/webpack.config.js#L169
- inside `webpack.config`, yoshi looks for a file named either `./server.*` or `../dev/server.*`: https://github.com/wix/yoshi/blob/master/packages/yoshi/config/webpack.config.js#L832
- importantly these are hardcoded https://github.com/wix/yoshi/blob/master/packages/yoshi/config/webpack.config.js#L169 and the `--server` arg is never passed into this section
- yoshi tells webpack to use that file as the root in the bundle's dependecy tree and to build the bundle into a final webpack entry object with the module `[name]` `server`: https://github.com/wix/yoshi/blob/master/packages/yoshi/config/webpack.config.js#L833 (https://webpack.js.org/concepts/entry-points/)
- the final server bundle will end up at `dist/server.js` because of these lines: https://github.com/wix/yoshi/blob/master/packages/yoshi/config/webpack.config.js#L838-L839 where the `BUILD_DIR` and module `[name]` are used to build the final filepath

#### Starting the server bundle
Then, in `start-app` the `server`/`entry-point` `cliArg` is used (and, importantly, the only time it's used) to fork a child process to start that same server bundle https://github.com/wix/yoshi/blob/master/packages/yoshi/src/commands/start-app.js#L100
- note that the default `cliArg.server` here is set to 'index.js' so, using the default, you'll never be able to run the server bundle because the lines here always name it `server.js`: https://github.com/wix/yoshi/blob/master/packages/yoshi/config/webpack.config.js#L838-L839 (`{ entry { server: ... } }`)
- so, the only way you can get the bundle to run is to call start with `--server=dist/server.js` because that's the only bundle that will be created


### The problem with an alternate entry point
More difficult to overcome trouble comes, like I mentioned above, when you _also_ have a second entry point you'd want to use for development (i.e. starting a testkit server).

It would be nice if you could specifiy where you'd want it to live and then use the `--server=server-alternate.js` cli arg to build it but the arg isn't passed to the webpack config and only `./server` and `../dev/server` are possible entry points.

But here's the thing on **the second entry point**: if you move your development entry point to `dev/server` so that it will be one of those two possible entry points, it can now be read and even start up - but **only if you don't have the other possible server entry point `server.js` in your project too**.

If you have both, the `server: possibleServerEntries.find(exists) || possibleServerEntries[0],` will `find` `server.js` first, transpile, and run that instead. So you'll never be able to run the second entry point even by moving it to `dev/`.


What I'm proposing is that you pass your `--server` cli argument, not just to start the bundle, but also to the webpack config that builds the bundle, so that you allow the dev to set the file used as the entry point. This would fix (1) the inability to run a second, dev configuration/entry-point and (2) give your users the flexibility they're likely expecting from the `--server` cli switch which is described as something you can use to "Pass a different value to start up a different script."

Like I say, I'm happy to make a PR if that would help or give us something to start with.

**Comment by ranyitz** [comment] 2019-08-13 07:16
@carl-e Nice write-up! It's cool that you've dived into the codebase. I'll try to address your comments:

> that's because there are only two possible, hard-coded base filenames that yoshi will use as a bundle entry point: server.{js,ts} or dev/server.{js,ts}. And, even if you use those hard-coded names, when you have both files the lookup will use .find(exists) and server.js is found first.

I prefer to call them **conventions** over "hard-coded base filenames", there are many benefits in a convention over configuration.

It seems you are trying to find a way to create two server bundles while this was never intended before and therefore would require a change in the code. (If we'll decide it's indeed the wanted behavior)

> I'd consider the server/entry-point cli argument to be broken/bugged because it's not actually being used for what it says it's for.

You are suggesting that the naming is bad? If that's the case, I tend to agree.
`--server` implies for the entry point of the server and `entry-point` creates disambiguation with webpack's `entry`. I think the best way to go here is to remove this CLI arg and replace with a convention.

> Let me back up. Let's say I have a setup that's a) as close as possible to the ideal situation for yoshi but b) has two different servers that a dev should be able to launch from our apps: server.js and dev/server.js

I just want to say that one of the **main** problems that Yoshi has today is the fact that it targets **many different types of projects** with a **single API**. I find it very confusing and the root cause of many misunderstandings like this.

In this case, we support:
1. **Client project** - This project is a client only, its server is developed in scala (or anything else...). Because we still need to serve it for development reasons we create a dev server or `dev/server` if you'd like.
2. **Fullstack project** - This project is a client + node server, the frontend team also manages a proxy server which returns the initial `html` file and accepts requires from the app, perform RPC calls etc.

It seems to me that your case is option 2 (Fullstack), in this case, we don't have a dev server. While it may be good to mock the real server for local development we went with a different method, using a testkit and running the real server. It's important to say that everything **can be changed**, we are open for ideas to improve those workflows!

> so, the only way you can get the bundle to run is to call start with --server=dist/server.js because that's the only bundle that will be created

That's true, this flow has started as experimental flow and I agree we should establish good defaults. We aim towards zero configuration and we should definitely solve this in the future.

> What I'm proposing is that you pass your --server cli argument, not just to start the bundle, but also to the webpack config that builds the bundle, so that you allow the dev to set the file used as the entry point...

That's one optional solution. Today there is a technical problem in making the `index.js` the entry for the server bundle. The problem is that the node platform APIs accepts a path to an express app (rather than a reference to it) making it impossible for Webpack to bundle its code. I know that the node platform team is working on changing that and when this problem is fixed from their side we'll be able to create a more coherent API when we know the server to run because it will always be the server bundle target.

____________________________________________

I'll summaries, I think that your feedback is super important and that you're pointing on some crucial problems that we have in Yoshi today. Changing the `--server`/`--entry-point` CLI parameter would be a breaking change, and therefore will need to be a part of the next version of Yoshi (5). Our direction is to remove it whatsoever and create a zero-configuration experience that just works. 

I do want to understand though, your workflow with fullstack project and a dev-server, why do you think it's better?

**Comment by carl-e** [comment] 2019-08-13 22:51
I completely understand wanting to simplify things.

We do have several fullstack projects that have been using yoshi for a while now. For each, we have two entry point scripts both of which call bootstrap and setup the express/SSR server for us. Normally, we have all local development hitting a vm that serves a local version of our backend.

The second script, however, also starts a testkit server alongside the SSR server. We've also found it very useful to have the option to have that testkit server serve those backend api points for things like providing different test data, e2e testing when the vm wouldn't be available, etc.

We're going to explore a bit more as there might be a way to start that server using a combination of the `start` hook and an environment variable. I'll update here on how that goes and whether or not we got something to work.

**Comment by carl-e** [comment] 2019-08-16 15:02
Ok, we're now able to optionally start our mock-api/testkit server from inside the main `src/server.js` entry point when an environment variable is set. Something close to:
```
if (process.env.TESTKIT) {
  // start mock api server
  ...
}
```

We then call it like this in an npm script `"start:optional": "TESTKIT=1 yoshi start --server=dist/server.js"`. It doesn't look like we need the start hook after all.

As a workaround, it seems to cover our use case and get us to the next steps.

Thanks for your responses, @ranyitz and explaining your approach.

**Comment by ranyitz** [comment] 2019-08-19 05:59
No problem @carl-e, and thanks for explaining your use-case.

A lot of things you've mentioned are problems that we plan on fixing in the future. hopefully, then you'll be able to use Yoshi without the need to look for workarounds.

closing

**Closed by ranyitz** 2019-08-19 05:59 UTC
Labels: 🗣 Discussion
