### ISSUE TITLE
windows support - create-yoshi-app

### ISSUE THREAD

**Issue by tzachvw** [wix/yoshi#1335] opened 2019-05-28 13:34 UTC
# 🙋 Feature Request

### 😯 Current Behavior

On Windows 10, when running:
1. npx create-yoshi-app my-app
2. npm install
3. npm start
3. npx jest --watch

the output is:
"No tests found, exiting with code 1"

although there are tests in the porject.

...

### 🤔 Expected Behavior

tests should be running.

...

### 💁 Possible Solution 

...

### 🔦 Context 

...

**Comment by ranyitz** [comment] 2019-07-01 19:28
Duplicate of #1345

**Closed by ranyitz** 2019-07-01 19:28 UTC
Labels: Windows
