### ISSUE TITLE
Use ignore-extensions file in Jest

### ISSUE THREAD

**Issue by tqmukas** [wix/yoshi#342] opened 2017-10-04 05:15 UTC
Those who use Jest, use https://github.com/wix-private/guineapig2/blob/master/package.json#L78 which is really redundant due to ignore extensions availability. In addition, in wallaby-jest file we already [use](https://github.com/wix/wix-node-build/blob/master/config/wallaby-jest.js#L6) ignore extensions, so it also makes inconsistency between the two runners.

ronami commented on Jan 25 • edited
Jest replaces the require function with a different function that doesn't support (and only mocks) require.extensions (https://github.com/facebook/jest/blob/ff2901636c271d9e7a2fdbb937adcce8e14635d1/packages/jest-runtime/src/index.js#L626).We can try to figure it out but for now I used some defaults for Jest: https://github.com/wix/wix-node-build/pull/56.

roymiloh commented on Jan 25
What's happening today if we import .png file and run jest? moreover, we have a [special handling for graphql](https://github.com/wix/wix-node-build/blob/master/lib/ignore-extensions.js#L27), how do we solve that?

ronami commented on Jan 25 • edited
I think we may have to maintain a similar version of our ignore-extensions.js as Jest configuration (see [facebook/jest#2017](https://github.com/facebook/jest/issues/2017#issuecomment-256849367) (comment) and [facebook/jest#2017](https://github.com/facebook/jest/issues/2017#issuecomment-257401462) (comment) for an explanation).

We can also try to think of a better solution.

**Comment by ronami** [comment] 2017-10-08 07:07
This is a duplicate of https://github.com/wix/yoshi/issues/309. We need to pre-configure Jest with our own defaults.

Closing, please re-open if I missed something.

**Closed by ronami** 2017-10-08 07:07 UTC
